language: cpp

os: linux

compiler: gcc

install:
    # Install dependencies
    - ./scripts/deps-ubuntu.sh

    # Start dummy MIDI server
    - jackd -d dummy &> /dev/null &

script:
    # Build and run tests
    - ./scripts/build.sh test
