language: cpp

install:
    # Install dependencies
    - ./scripts/deps.sh

    # Start dummy MIDI server
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then jackd -d dummy > /dev/null & fi

script:
    # Build and run tests
    - ./scripts/build.sh test
